import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import { ClerkProvider, currentUser, SignOutButton } from "@clerk/nextjs";

import ModeToggle from "~/components/mode-toggle";
import ThemeProvider from "~/components/theme-provider";
import { Button } from "~/components/ui/button";
import { Separator } from "~/components/ui/separator";
import { cn } from "~/lib/utils";

import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Reddit Clone (by Ryan Macdonald)",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  const user = await currentUser();

  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body
          className={cn("bg-background font-sans antialiased", inter.className)}
        >
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <div className="h-full flex-col">
              <nav className="fixed left-0 top-0 flex h-12 w-full items-center justify-between bg-background px-8">
                <span className="text-xl font-semibold">reddit.</span>

                {user ? (
                  <div className="flex items-center gap-4">
                    <span>Welcome, {user.firstName}</span>
                    <SignOutButton>
                      <Button>Sign Out</Button>
                    </SignOutButton>
                  </div>
                ) : (
                  <div className="flex items-center gap-2">
                    <Link href="/sign-up">
                      <Button variant="outline">Sign Up</Button>
                    </Link>
                    <Link href="/sign-in">
                      <Button variant="secondary">Sign In</Button>
                    </Link>
                  </div>
                )}
              </nav>
              <Separator className="fixed left-0 top-12" />
              <main className="my-12 px-4 py-2">{children}</main>
              <Separator className="fixed bottom-12 left-0" />
              <footer className="fixed bottom-0 left-0 flex h-12 w-full items-center justify-between bg-background px-4">
                <ModeToggle />
                <span className="font-mono text-sm">
                  by{" "}
                  <a href="https://github.com/iamryanmacdonald">
                    Ryan Macdonald
                  </a>
                </span>
              </footer>
            </div>
            {modal}
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
